// js/core/sim.js
// Simulation core with A* pathfinding integration
(function(){
  // reuse MAP from main.js (global) or provide default
  if(typeof MAP==='undefined') window.MAP={width:30,height:20,tiles:[]};

  function idx(x,y){return Math.floor(y)*MAP.width+Math.floor(x)}

  class Citizen{constructor(id,x,y,skill){this.id=id;this.x=x;this.y=y;this.skill=skill||1;this.money=100;this.happiness=1;this.job=null;this.path=null;this.pathIndex=0;this.speed=0.08;}}

  class Company{constructor(id,name,x,y){this.id=id;this.name=name;this.x=x;this.y=y;this.funds=2000;this.materials=500;this.openings=[]} postJob(skill,wage){const jid=`J${Date.now()}${Math.floor(Math.random()*99)}`;const j={id:jid,companyId:this.id,skillReq:skill,wage:wage,filled:null};SIM.jobs[jid]=j;this.openings.push(jid);SIM.log(`${this.name} posts ${jid}`);return j}}

  class Site{constructor(id,companyId,x,y,required,cost){this.id=id;this.companyId=companyId;this.x=x;this.y=y;this.required=required||200;this.progress=0;this.cost=cost||200;this.status='planned'} start(company){if(this.status!=='planned'&&this.status!=='waiting')return false;if(company.materials>=this.cost){company.materials-=this.cost;this.status='ongoing';SIM.log(`Site ${this.id} started`);return true}else{this.status='waiting';return false}} applyWork(h){if(this.status!=='ongoing')return;this.progress+=h;if(this.progress>=this.required){this.status='done';SIM.log(`Site ${this.id} finished`)}}}

  const SIM={ticks:0,citizens:[],companies:[],sites:[],jobs:{},logLines:[],log(s){this.logLines.unshift(`[${this.ticks}] ${s}`); if(this.logLines.length>400)this.logLines.pop()},addCitizen(skill,x,y){const id=`C${this.citizens.length}`;const cx=(x!==undefined?x:(Math.random()*MAP.width));const cy=(y!==undefined?y:(Math.random()*MAP.height));const c=new Citizen(id,cx,cy,skill||(1+Math.floor(Math.random()*6)));this.citizens.push(c);this.log(`Add ${id} s=${c.skill}`);return c},addCompany(name,x,y){const id=`CO${this.companies.length}`;const c=new Company(id,name||`Company ${this.companies.length}`,x||8+Math.random()*12,y||3+Math.random()*12);this.companies.push(c);this.log(`Add company ${c.name}`);return c},addSite(companyId,x,y,req,cost){const id=`S${this.sites.length}`;const co=this.companies.find(c=>c.id===companyId); if(!co)return null; const s=new Site(id,companyId,x||co.x+Math.random()*2-1,y||co.y+Math.random()*2-1,req||200,cost||200); this.sites.push(s); this.log(`Add site ${id}`); return s},findOpenJobs(){return Object.values(this.jobs).filter(j=>!j.filled)},match(){const open=this.findOpenJobs().sort((a,b)=>b.wage-a.wage);for(const c of this.citizens){if(c.job)continue; let best=null; let bestScore=-1; for(const j of open){ if(c.skill<j.skillReq) continue; const co=this.companies.find(x=>x.id===j.companyId); const dist=Math.hypot(c.x-co.x,c.y-co.y)+1; const score=j.wage/dist; if(score>bestScore){bestScore=score; best=j}} if(best){best.filled=c.id; c.job=best.id; // compute path to a near ongoing site of company or to company center
          const site=this.sites.find(s=>s.companyId===best.companyId && s.status==='ongoing'); const target=(site? [site.x,site.y]:[Math.floor(this.companies.find(cc=>cc.id===best.companyId).x),Math.floor(this.companies.find(cc=>cc.id===best.companyId).y)]);
          const path=AStar.findPath([Math.floor(c.x),Math.floor(c.y)], target, MAP);
          c.path=path; c.pathIndex=0; this.log(`${c.id} hired->${best.id}`)}}},pay(){for(const id in this.jobs){const j=this.jobs[id]; if(j.filled){const co=this.companies.find(c=>c.id===j.companyId); const w=this.citizens.find(c=>c.id===j.filled); if(co.funds>=j.wage){co.funds-=j.wage; w.money+=j.wage}else{w.happiness-=0.05; this.log(`${co.name} can't pay ${j.id}`)}}}},work(){for(const co of this.companies){const coSites=this.sites.filter(s=>s.companyId===co.id && s.status==='ongoing'); if(coSites.length===0) continue; const empJobs=co.openings.map(id=>this.jobs[id]).filter(j=>j&&j.filled); for(const j of empJobs){const worker=this.citizens.find(c=>c.id===j.filled); if(!worker) continue; // follow path
        if(worker.path && worker.pathIndex < worker.path.length){ const node=worker.path[worker.pathIndex]; const tx=node[0]+0.5, ty=node[1]+0.5; const dx=tx-worker.x, dy=ty-worker.y; const d=Math.hypot(dx,dy); if(d<0.07){worker.pathIndex++;} else { worker.x += dx/d*worker.speed; worker.y += dy/d*worker.speed; continue; } }
        // if arrived, contribute to nearest site
        const site = coSites[0]; const prod = 1*(1+(worker.skill-1)*0.2); site.applyWork(prod);
      }}},events(){if(Math.random()<0.012){const co=this.companies[(Math.random()*this.companies.length)|0]; const gain=200+Math.floor(Math.random()*1000); co.funds+=gain; this.log(`${co.name} gets contract +${gain}`)} if(Math.random()<0.006){const s=this.sites[(Math.random()*this.sites.length)|0]; if(s&&s.status==='ongoing'){s.status='waiting'; this.log(`Site ${s.id} lacks materials`)}}},cleanup(){for(const id in this.jobs){const j=this.jobs[id]; if(j.filled){const w=this.citizens.find(c=>c.id===j.filled); if(!w || w.happiness<=0){ if(w) w.job=null; j.filled=null; this.log(`${j.filled||'?' } left ${j.id}`)}}}},tick(){this.ticks++; for(const co of this.companies) if(co.funds>300 && Math.random()<0.03){ const sk=1+Math.floor(Math.random()*5); const w=3+Math.floor(Math.random()*8); const j=co.postJob?co.postJob(sk,w):null; if(j) co.openings.push(j.id) } for(const s of this.sites){ const co=this.companies.find(c=>c.id===s.companyId); s.start(co) } this.match(); this.pay(); this.work(); for(const c of this.citizens) c.money-=0.05; this.events(); this.cleanup(); if(this.ticks%30===0) this.log(`Summary ticks=${this.ticks} citizens=${this.citizens.length}`)} };

  window.SIM=SIM;
})();
